In [1]:
import pandas as pd

df = pd.read_csv(r"D:\PythonTraining\PayFailIntel\outputs\final_failed_transactions.csv")
df.head()

,txn_id,user_id,merchant_id,bank_id,txn_time,amount,status,failure_reason,bank_name,server_status,merchant_name,category,user_name,user_city,document
0,30e2c03e-a070-4076-afa6-e7e7c0448834,897,120,17,2025-01-01 14:59:00,1945.26,FAILED,CARD_DECLINED,Standard Chartered,DOWN,Roach-Edwards,Grocery,Rose Foster,Normanhaven,\nTransaction ID: 30e2c03e-a070-4076-afa6-e7e7...
1,06a16bff-daca-4322-8209-9b2f5d4ddc0a,409,195,5,2025-06-17 17:01:00,5958.95,FAILED,CARD_DECLINED,Kotak,DELAYED,"Armstrong, Adams and Dunlap",Grocery,Margaret Bates,Port Ricardo,\nTransaction ID: 06a16bff-daca-4322-8209-9b2f...
2,cfe8af4a-6bf2-482d-8f49-91af62f352af,825,114,12,2024-11-09 21:20:00,9051.04,FAILED,INVALID_PIN,IDFC,ONLINE,Collins-Evans,Travel,Amber Cooper,Kramerville,\nTransaction ID: cfe8af4a-6bf2-482d-8f49-91af...
3,9d791a99-1ccd-4f15-95fd-14668d8e70c9,462,86,17,2024-07-21 17:54:00,8163.24,FAILED,TIMEOUT,Standard Chartered,DOWN,Myers Group,Ecommerce,Kelly Bruce,West Cindy,\nTransaction ID: 9d791a99-1ccd-4f15-95fd-1466...
4,ab3104f8-8187-44cf-bd19-a78f6d374871,22,66,12,2024-07-13 02:22:00,535.25,FAILED,CARD_DECLINED,IDFC,ONLINE,Berg-Ramos,Fashion,Vincent Lynn,Triciamouth,\nTransaction ID: ab3104f8-8187-44cf-bd19-a78f...

In [2]:
df['failure_reason'].value_counts()

failure_reason
CARD_DECLINED         1262
INVALID_PIN           1260
INSUFFICIENT_FUNDS    1232
TIMEOUT               1200
Name: count, dtype: int64

In [3]:
df['bank_name'].value_counts()

bank_name
City Union            270
IndusInd              263
AU Small              262
Canara                261
PNB                   259
HSBC                  253
Kotak                 253
Yes Bank              253
RBL                   251
ICICI                 251
DBS                   250
Union Bank            248
SBI                   247
HDFC                  246
UCO                   243
Standard Chartered    242
BOB                   235
IDFC                  227
Axis                  225
South Indian Bank     215
Name: count, dtype: int64

In [4]:
df['merchant_name'].value_counts().head(20)

merchant_name
Patrick, Johnson and Miller        38
Armstrong, Adams and Dunlap        37
Garcia, Clark and Wiley            36
Yates LLC                          34
Campbell, Carroll and Valentine    34
Crawford Ltd                       33
Huff PLC                           33
Huynh and Sons                     32
Frey LLC                           32
Martinez PLC                       32
Schmidt Ltd                        31
Atkinson-Scott                     31
Mason, Smith and Campbell          31
Stephens-Mendoza                   31
Burton-Sanchez                     31
Willis Group                       30
King-Morrow                        30
Martin, Allen and James            30
Everett, Knox and Allen            30
Gardner-Deleon                     30
Name: count, dtype: int64

In [5]:
df['category'].value_counts()

category
Food             931
Grocery          864
Ecommerce        741
Travel           711
Fashion          678
Entertainment    536
Health           493
Name: count, dtype: int64

In [6]:
df['user_city'].value_counts().head(20)

user_city
New John             25
Russellton           15
South Danielle       15
Tylerfort            15
South Jennifer       15
South Michael        14
West Jennifer        13
West Brooke          13
Michaelmouth         13
Lake Scott           13
Randallstad          13
Port Heather         13
South Manuelville    12
Kellyberg            12
New James            12
East Kellystad       12
Lake Ronald          12
Port Nicholeville    12
Grantfort            11
Evansshire           11
Name: count, dtype: int64

In [7]:
df.groupby(['bank_name', 'failure_reason']).size().sort_values(ascending=False)

bank_name           failure_reason
Canara              CARD_DECLINED         78
City Union          INVALID_PIN           78
PNB                 CARD_DECLINED         78
RBL                 INSUFFICIENT_FUNDS    77
ICICI               TIMEOUT               75
                                          ..
Standard Chartered  CARD_DECLINED         47
IDFC                TIMEOUT               46
Axis                TIMEOUT               46
BOB                 INSUFFICIENT_FUNDS    45
South Indian Bank   TIMEOUT               41
Length: 80, dtype: int64

In [8]:
df.groupby(['category', 'failure_reason']).size().sort_values(ascending=False)

category       failure_reason
Food           INVALID_PIN           244
Grocery        CARD_DECLINED         243
Food           CARD_DECLINED         238
               INSUFFICIENT_FUNDS    238
Grocery        INVALID_PIN           214
Food           TIMEOUT               211
Grocery        INSUFFICIENT_FUNDS    204
               TIMEOUT               203
Travel         TIMEOUT               199
Ecommerce      CARD_DECLINED         190
               INSUFFICIENT_FUNDS    188
               TIMEOUT               185
Travel         INVALID_PIN           181
Fashion        INSUFFICIENT_FUNDS    179
Ecommerce      INVALID_PIN           178
Fashion        CARD_DECLINED         173
               INVALID_PIN           173
Travel         CARD_DECLINED         168
               INSUFFICIENT_FUNDS    163
Fashion        TIMEOUT               153
Entertainment  INVALID_PIN           142
               INSUFFICIENT_FUNDS    139
               TIMEOUT               136
Health         CARD_DECLINED         131
               INVALID_PIN           128
               INSUFFICIENT_FUNDS    121
Entertainment  CARD_DECLINED         119
Health         TIMEOUT               113
dtype: int64

What FAISS sees each Record as:

In [9]:
print(df.iloc[0]['document'])

Transaction ID: 30e2c03e-a070-4076-afa6-e7e7c0448834
Timestamp: 2025-01-01 14:59:00
Amount: 1945.26
Status: FAILED
Failure Reason: CARD_DECLINED
Bank: Standard Chartered (Server: DOWN)
Merchant: Roach-Edwards (Grocery)
User City: Normanhaven

In [10]:
df.sample(10)[['failure_reason', 'bank_name', 'merchant_name', 'category', 'amount']]

,failure_reason,bank_name,merchant_name,category,amount
979,CARD_DECLINED,PNB,Flores-Jefferson,Travel,1869.60
518,INSUFFICIENT_FUNDS,AU Small,Adams-Smith,Health,460.93
481,TIMEOUT,Yes Bank,Jordan-Lozano,Entertainment,9210.92
100,INVALID_PIN,DBS,Martin Ltd,Travel,3283.18
2304,INVALID_PIN,AU Small,Smith-Casey,Entertainment,6302.69
2512,INSUFFICIENT_FUNDS,AU Small,"Clark, Paul and Duncan",Ecommerce,4800.10
3795,INSUFFICIENT_FUNDS,Axis,"Rivera, Small and Martinez",Fashion,8028.33
4447,INSUFFICIENT_FUNDS,HSBC,"Sanchez, Parker and Long",Grocery,432.90
681,CARD_DECLINED,Union Bank,Odonnell-Lowery,Ecommerce,3700.97
767,CARD_DECLINED,South Indian Bank,King-Morrow,Grocery,9377.66